name: Test Github Actions Linux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'

    - name: Install RP2040 SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DPICO_PLATFORM=rp2040 -DPICO_SDK_PATH=$PICO_SDK_PATH

    - name: Build firmware
      run: |
        cd build
        make

    - name: Generate release files
      run: |
        cd build
        arm-none-eabi-objcopy -O ihex Coremark-RP2040.elf Coremark-RP2040.hex
        arm-none-eabi-objcopy -O binary Coremark-RP2040.elf Coremark-RP2040.bin
        $PICO_SDK_PATH/build/elf2uf2/elf2uf2 Coremark-RP2040.elf Coremark-RP2040.uf2
